services:
  - type: web
    name: dashnotes
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.2
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 3000
